apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: ghcr.io/muhammadjaffar52/frontend
    newTag: latest

  - name: ghcr.io/muhammadjaffar52/gateway
    newTag: latest

  - name: ghcr.io/muhammadjaffar52/user-service
    newTag: latest

  - name: ghcr.io/muhammadjaffar52/product-service
    newTag: latest

  - name: ghcr.io/muhammadjaffar52/order-service
    newTag: latest

  - name: ghcr.io/muhammadjaffar52/payment-service
    newTag: latest

replicas:
  - name: frontend
    count: 1

  - name: gateway
    count: 1

  - name: user-service
    count: 1

  - name: product-service
    count: 1

  - name: order-service
    count: 1

  - name: payment-service
    count: 1