apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubectl.kubernetes.io/restartedAt: "2026-07-15T13:47:19+05:00"
  creationTimestamp: "2026-07-15T08:47:20Z"
  generateName: payment-service-5ccfdc48f9-
  labels:
    app: payment-service
    pod-template-hash: 5ccfdc48f9
  name: payment-service-5ccfdc48f9-6xbvn
  namespace: microservices
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: payment-service-5ccfdc48f9
    uid: b8b74823-6067-435b-a98b-0881ef1175c2
  resourceVersion: "85274"
  uid: c6796a65-e2e1-44de-897d-41fbb90189f1
spec:
  containers:
  - envFrom:
    - configMapRef:
        name: payment-service-config
    image: localhost:5001/payment-service:1.0
    imagePullPolicy: IfNotPresent
    livenessProbe:
      failureThreshold: 3
      httpGet:
        path: /health
        port: 3004
        scheme: HTTP
      initialDelaySeconds: 15
      periodSeconds: 20
      successThreshold: 1
      timeoutSeconds: 1
    name: payment-service
    ports:
    - containerPort: 3004
      protocol: TCP
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /health
        port: 3004
        scheme: HTTP
      initialDelaySeconds: 5
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 1
    resources:
      limits:
        cpu: 250m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-rpgtn
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: cloudnative-worker2
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-rpgtn
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2026-07-15T08:47:23Z"
    status: "True"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2026-07-15T08:47:20Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2026-07-15T08:47:30Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2026-07-15T08:47:30Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2026-07-15T08:47:20Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://9e17fa9735ff29b221cb3dcec28525544bb230d02f04826be7144a7ff52ba632
    image: localhost:5001/payment-service:1.0
    imageID: localhost:5001/payment-service@sha256:9bab830a82f835e2eaee66c1e808039bd9983fb07b9593477933ad75d3c208c9
    lastState: {}
    name: payment-service
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2026-07-15T08:47:22Z"
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-rpgtn
      readOnly: true
      recursiveReadOnly: Disabled
  hostIP: 172.18.0.4
  hostIPs:
  - ip: 172.18.0.4
  phase: Running
  podIP: 10.244.2.20
  podIPs:
  - ip: 10.244.2.20
  qosClass: Burstable
  startTime: "2026-07-15T08:47:20Z"
