apiVersion: apps/v1
kind: Deployment

metadata:

  name: gateway

  namespace: microservices


spec:

  replicas: 1


  selector:

    matchLabels:

      app: gateway


  template:

    metadata:

      labels:

        app: gateway 
    
    spec:
      serviceAccountName: app-sa

    

      containers:


      - name: gateway


        image: ghcr.io/muhammadjaffar52/gateway:sha-e512e2b

        imagePullPolicy: IfNotPresent


        ports:

        - containerPort: 8000



        envFrom:

        - configMapRef:

            name: gateway-config



        resources:


          requests:

            cpu: "100m"

            memory: "128Mi"


          limits:

            cpu: "250m"

            memory: "256Mi"



        readinessProbe:

          httpGet:

            path: /health

            port: 8000


          initialDelaySeconds: 5

          periodSeconds: 10



        livenessProbe:

          httpGet:

            path: /health

            port: 8000


          initialDelaySeconds: 15

          periodSeconds: 20