apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: microservices-dev
  namespace: argocd

spec:
  project: applications

  source:
    repoURL: https://github.com/MuhammadJaffar52/cloudnative-platform.git
    targetRevision: main
    path: kubernetes/overlays/dev

  destination:
    server: https://kubernetes.default.svc
    namespace: microservices-dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true