apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - gateway.yaml
  - destinationrule-canary.yaml
  - virtualservice-canary.yaml
  - destinationrule-bluegreen.yaml
  - virtualservice-bluegreen.yaml 
  - telemetry.yaml
  - serviceentry-postgres.yaml
  - destinationrule-postgres.yaml
