apiVersion: apps/v1
kind: Deployment

metadata:
  name: user-service
  namespace: microservices

spec:
  replicas: 1

  selector:
    matchLabels:
      app: user-service

  template:
    metadata:
      labels:
        app: user-service

    spec:
      containers:
        - name: user-service
          image: localhost:5001/user-service:1.0
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 3001

          envFrom:
            - configMapRef:
                name: user-service-config

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"

          readinessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 5
            periodSeconds: 10

          livenessProbe:
            httpGet:
              path: /health
              port: 3001
            initialDelaySeconds: 15
            periodSeconds: 20