apiVersion: argoproj.io/v1alpha1
kind: AppProject

metadata:
  name: applications
  namespace: argocd

spec:
  description: Application Workloads Project

  # Allow applications from any Git repository
  sourceRepos:
    - '*'

  # Allow deployment to any namespace in the local cluster
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc

  # Allow all namespace-scoped resources
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'

  # Allow all cluster-scoped resources
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'

  # No orphaned resource warnings
  orphanedResources:
    warn: false