apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - serviceaccount/shared-sa.yaml

  - rbac/shared-role.yaml
  - rbac/shared-rolebinding.yaml

  - secrets/app-secret.yaml
  - network-policies/default-deny.yaml
  - network-policies/gateway-to-user.yaml
  - network-policies/istio-ingress-to-frontend.yaml